[build]
  command = "npm run build"
  # Ne pas définir de répertoire 'publish' ici. 
  # Le plugin @netlify/plugin-nextjs v5 détecte et gère automatiquement la sortie de Next.js.

[[plugins]]
  package = "@netlify/plugin-nextjs"
